#!/usr/bin/expect -f
set timeout 15
spawn ssh -o StrictHostKeyChecking=no -p 57906 -i ~/vastai root@184.144.255.144 "strace -e trace=file -f -p \$(pgrep noland-state-a) > /tmp/strace.log 2>&1 & sleep 1; echo '{\"id\": \"1\", \"method\": \"ListApps\", \"params\": {}}' | nc -U /run/noland/state-agent.sock; killall strace"
expect {
    "Enter passphrase for key" {
        send "Casa8301\r"
        exp_continue
    }
    eof
}
