#!/usr/bin/expect -f
set timeout 300
spawn scp -o StrictHostKeyChecking=no -P 61761 -i ~/vastai agent.tar.gz root@142.170.96.180:/tmp/noland-state-agent.tar.gz
expect {
    "Enter passphrase for key" {
        send "Casa8301\r"
        exp_continue
    }
    eof
}
spawn scp -o StrictHostKeyChecking=no -P 61761 -i ~/vastai state-agent/scripts/bootstrap-remote.sh root@142.170.96.180:/tmp/bootstrap-remote.sh
expect {
    "Enter passphrase for key" {
        send "Casa8301\r"
        exp_continue
    }
    eof
}
spawn ssh -o StrictHostKeyChecking=no -p 61761 -i ~/vastai root@142.170.96.180 "chmod +x /tmp/bootstrap-remote.sh && /tmp/bootstrap-remote.sh /tmp/noland-state-agent.tar.gz user"
expect {
    "Enter passphrase for key" {
        send "Casa8301\r"
        exp_continue
    }
    eof
}
